config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :seats, only: [:index, :update] do
    put 'reserve', on: :collection
  end
  root 'seats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :seats
end

app/models/seat.rb
class Seat < ApplicationRecord
    belongs_to :room

    enum status: { livre: 0, reservado: 1, selecionado: 2, selecionado_por_outro: 3 }
    validates :x, :y, :room_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SeatsHelper
end

app/controllers/seats_controller.rb
# app/controllers/seats_controller.rb
class SeatsController < ApplicationController

  def index
    @seats = Room.first.seats
  end

  def update
    @seat = Room.first.seats.find(params[:id])
    if @seat.reservado?
      flash[:error] = 'This seat is already reserved!'
    else
      if @seat.selecionado?
        @seat.livre!
      elsif @seat.livre?
        @seat.selecionado!
      end
      session[:selected_seat_id] = @seat.id
    end
    broadcast_seat_update(@seat, session.id)
    redirect_back(fallback_location: seats_path)
  end

  def reserve
    @seats = Room.first.seats.where(id: params[:ids])
  if @seats.any? { |seat| seat.reservado?}
      redirect_back(fallback_location: seats_path, alert: 'This seat is already reserved.')
    else
      @seats = Room.first.seats.where(status: 2)
      @seats.update_all(status: 1)
      @seats.each { |seat| broadcast_seat_update(seat, session.id) }
      redirect_to root_path
    end
  end

  private

  def seat_params
    params.require(:seat).permit(:status)
  end

  def broadcast_seat_update(seat, session_id)
    room_id = seat.room_id
    puts "Broadcasting to room_#{room_id}, Session ID: #{session_id}, Seat ID: #{seat.id}, Status: #{seat.status}"
    ActionCable.server.broadcast("room_#{room_id}", { session_id: { public_id: session_id}, seat_id: seat.id, status: seat.status })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
    def seat_status(seat)
      case seat.status
      when 'livre'
        'livre'
      when 'reservado'
        'reservado'
      when 'selecionado'
        'selecionado'
      when 'selecionado_por_outro'
        'selecionado_por_outro'
      end
    end

    def seat_color(seat)
        case seat.status
        when 'livre'
          'green'
        when 'reservado'
          'red'
        when 'selecionado'
          'lightgrey'
        when 'selecionado_por_outro'
          'lightcoral'
        end
      end
  end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoopCoChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seats/index.html.erb
<!-- app/views/seats/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Seat Reservation</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
  <h1 class="display-4 text-left my-4"><%= Room.first.name %></h1>
  <h4 class="mb-4">Selecione os lugares que pretende reservar</h4>
  <div style="display: flex; flex-wrap: wrap; max-width: 600px;">
    <% @seats.order(:id).each_slice(20) do |row| %>
      <div style="display: flex;">
        <% row.each do |seat| %>
          <div id="circle-<%= seat.id%>" style="cursor: pointer; margin: 5px; width: 30px; height: 30px; border-radius: 50%; background-color: <%= seat_color(seat) %>; display: flex; align-items: center; justify-content: center;" onclick="selectSeat(<%= seat.id %>)">
            <p id="circle-value-<%= seat.id%>" style="text-align: center;"><%= seat.id %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <form id="seat-selection-form" action="" method="post" style="display: none;">
    <input type="hidden" name="_method" value="put">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" id="room-id" data-room-id="<%= Room.first.id %>" />
  </form>

  <div class="d-flex justify-content-start mt3">
    <% if Room.first.seats.any? { |seat| seat.status == 'selecionado' } %>
      <h5 class="align-self-center mr-2">Reserve já: </h5>
      <%= button_to 'Reservar', reserve_seats_path, method: :put, remote: true %>
    <% end %>
  </div>

  <script>
    if (!window.currentUserId) {
      let currentUserId = "<%= session.id %>";
      window.currentUserId = currentUserId;
    }

  function selectSeat(seatId) {
    // Update the action attribute of the form
    const form = document.getElementById('seat-selection-form');
    form.action = `/seats/${seatId}`;

    // Submit the form
    form.submit();
  }
</script>

</body>
</html>